import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1784291437710 implements MigrationInterface {
    name = 'InitSchema1784291437710'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."admin_unit_type" AS ENUM('PROVINCE', 'WARD')`);
        await queryRunner.query(`CREATE TABLE "administrative_units" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(20) NOT NULL, "name" character varying(150) NOT NULL, "type" "public"."admin_unit_type" NOT NULL, "parent_id" uuid, CONSTRAINT "UQ_78ee5a7835ce8072e55a8493895" UNIQUE ("code"), CONSTRAINT "PK_97f662b9b848ae0982347d7d1d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_admin_units_type" ON "administrative_units"  ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_admin_units_parent" ON "administrative_units"  ("parent_id") `);
        await queryRunner.query(`CREATE TYPE "public"."agency_level" AS ENUM('CENTRAL', 'PROVINCE', 'WARD')`);
        await queryRunner.query(`CREATE TABLE "government_agencies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "level" "public"."agency_level" NOT NULL, "parent_id" uuid, "admin_unit_id" uuid, "address" character varying(500), "phone" character varying(30), "email" character varying(255), "website" character varying(255), CONSTRAINT "UQ_c510cb58b450566285d814400e9" UNIQUE ("code"), CONSTRAINT "PK_a7dcc53eda880b841f6f8edb87f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_gov_agencies_level" ON "government_agencies"  ("level") `);
        await queryRunner.query(`CREATE INDEX "idx_gov_agencies_parent" ON "government_agencies"  ("parent_id") `);
        await queryRunner.query(`CREATE TYPE "public"."requirement_type" AS ENUM('DOCUMENT', 'CONDITION')`);
        await queryRunner.query(`CREATE TABLE "procedure_requirements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "procedure_id" uuid NOT NULL, "name" character varying(500) NOT NULL, "requirement_type" "public"."requirement_type" NOT NULL DEFAULT 'DOCUMENT', "quantity" integer NOT NULL DEFAULT '1', "note" character varying(500), "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_44ff30c6fc48bfc41b24d90991e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_procedure_requirements_procedure" ON "procedure_requirements"  ("procedure_id") `);
        await queryRunner.query(`CREATE TABLE "procedure_steps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "procedure_id" uuid NOT NULL, "step_number" integer NOT NULL, "title" character varying(255) NOT NULL, "description" text, CONSTRAINT "uq_procedure_steps_order" UNIQUE ("procedure_id", "step_number"), CONSTRAINT "PK_78ec04e53a1e71dd42b2cd452fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_procedure_steps_procedure" ON "procedure_steps"  ("procedure_id") `);
        await queryRunner.query(`CREATE TYPE "public"."online_level" AS ENUM('MUC_2', 'MUC_3', 'MUC_4')`);
        await queryRunner.query(`CREATE TYPE "public"."procedure_status" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "administrative_procedures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(50) NOT NULL, "name" character varying(500) NOT NULL, "description" text, "agency_id" uuid, "online_level" "public"."online_level", "fee_text" character varying(500), "processing_time_text" character varying(255), "legal_basis_text" text, "status" "public"."procedure_status" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "UQ_efc833b7b892f26462a7bec0669" UNIQUE ("code"), CONSTRAINT "PK_9f76c9e50e95d8fa7045d592a02" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_procedures_name" ON "administrative_procedures"  ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_procedures_agency" ON "administrative_procedures"  ("agency_id") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(100) NOT NULL, "name" character varying(150) NOT NULL, "module" character varying(50) NOT NULL, CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(50) NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(255), CONSTRAINT "UQ_f6d54f95c31b73fb1bdd8e91d0c" UNIQUE ("code"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_status" AS ENUM('ACTIVE', 'INACTIVE', 'BANNED')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "version" integer NOT NULL, "email" character varying(255) NOT NULL, "password_hash" character varying(255), "full_name" character varying(255) NOT NULL, "phone" character varying(20), "status" "public"."user_status" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_users_email" ON "users"  ("email") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."conversation_channel" AS ENUM('CHAT', 'VOICE')`);
        await queryRunner.query(`CREATE TYPE "public"."conversation_status" AS ENUM('ACTIVE', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "version" integer NOT NULL, "user_id" uuid NOT NULL, "title" character varying(255), "channel" "public"."conversation_channel" NOT NULL DEFAULT 'CHAT', "status" "public"."conversation_status" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_conversations_user" ON "conversations"  ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."document_purpose" AS ENUM('CHAT_ATTACHMENT', 'OCR_INPUT', 'KB_SOURCE', 'AVATAR')`);
        await queryRunner.query(`CREATE TYPE "public"."ocr_status" AS ENUM('NONE', 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "version" integer NOT NULL, "owner_id" uuid, "storage_key" character varying(500) NOT NULL, "file_name" character varying(255) NOT NULL, "mime_type" character varying(100) NOT NULL, "size_bytes" bigint NOT NULL, "purpose" "public"."document_purpose" NOT NULL, "ocr_status" "public"."ocr_status" NOT NULL DEFAULT 'NONE', "extracted_text" text, "extracted_data" jsonb, "ocr_error" character varying(500), CONSTRAINT "UQ_c0acf262e5848697810c8e9f732" UNIQUE ("storage_key"), CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_documents_owner" ON "documents"  ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "idx_documents_purpose" ON "documents"  ("purpose") `);
        await queryRunner.query(`CREATE TYPE "public"."message_sender_role" AS ENUM('USER', 'ASSISTANT', 'SYSTEM')`);
        await queryRunner.query(`CREATE TYPE "public"."message_content_type" AS ENUM('TEXT', 'AUDIO', 'IMAGE')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "conversation_id" uuid NOT NULL, "sender_role" "public"."message_sender_role" NOT NULL, "content" text NOT NULL, "content_type" "public"."message_content_type" NOT NULL DEFAULT 'TEXT', "document_id" uuid, "metadata" jsonb, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_messages_conversation_created" ON "messages"  ("conversation_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "feedbacks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "message_id" uuid NOT NULL, "user_id" uuid NOT NULL, "rating" smallint NOT NULL, "comment" character varying(1000), CONSTRAINT "uq_feedbacks_message_user" UNIQUE ("message_id", "user_id"), CONSTRAINT "PK_79affc530fdd838a9f1e0cc30be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_feedbacks_user" ON "feedbacks"  ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."training_data_source" AS ENUM('FEEDBACK', 'CONVERSATION', 'MANUAL')`);
        await queryRunner.query(`CREATE TYPE "public"."training_data_status" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "ai_training_data" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "source_type" "public"."training_data_source" NOT NULL, "input_text" text NOT NULL, "expected_output" text, "feedback_id" uuid, "status" "public"."training_data_status" NOT NULL DEFAULT 'PENDING', "review_note" character varying(1000), CONSTRAINT "PK_7457152719d8016698e4d141d20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ai_training_data_source" ON "ai_training_data"  ("source_type") `);
        await queryRunner.query(`CREATE INDEX "idx_ai_training_data_status" ON "ai_training_data"  ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."gender" AS ENUM('MALE', 'FEMALE', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "citizen_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "version" integer NOT NULL, "user_id" uuid NOT NULL, "national_id" character varying(20), "date_of_birth" date, "gender" "public"."gender", "province_id" uuid, "ward_id" uuid, "address_detail" character varying(500), CONSTRAINT "REL_74180041ad4437e4b389830a81" UNIQUE ("user_id"), CONSTRAINT "PK_40611f4ad750c47bd2744694bbd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_citizen_profiles_user" ON "citizen_profiles"  ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_citizen_profiles_national_id" ON "citizen_profiles"  ("national_id") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."kb_source_type" AS ENUM('LEGAL_DOCUMENT', 'PROCEDURE', 'AGENCY')`);
        await queryRunner.query(`CREATE TABLE "kb_chunks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "source_type" "public"."kb_source_type" NOT NULL, "source_id" uuid NOT NULL, "chunk_index" integer NOT NULL, "content" text NOT NULL, "embedding" real array, "token_count" integer, CONSTRAINT "uq_kb_chunks_source_index" UNIQUE ("source_type", "source_id", "chunk_index"), CONSTRAINT "PK_de84c3fce0c1a29928e98441cd3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_kb_chunks_source" ON "kb_chunks"  ("source_type") `);
        await queryRunner.query(`CREATE TYPE "public"."legal_doc_type" AS ENUM('LUAT', 'NGHI_DINH', 'THONG_TU', 'QUYET_DINH', 'KHAC')`);
        await queryRunner.query(`CREATE TYPE "public"."legal_doc_status" AS ENUM('CON_HIEU_LUC', 'HET_HIEU_LUC', 'CHUA_HIEU_LUC')`);
        await queryRunner.query(`CREATE TABLE "legal_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(100) NOT NULL, "title" character varying(500) NOT NULL, "doc_type" "public"."legal_doc_type" NOT NULL, "issuing_body" character varying(255) NOT NULL, "issued_date" date, "effective_date" date, "expiry_date" date, "status" "public"."legal_doc_status" NOT NULL DEFAULT 'CON_HIEU_LUC', "source_url" character varying(500), "summary" text, CONSTRAINT "UQ_89b539d320ccd8b5ff439b6dec3" UNIQUE ("code"), CONSTRAINT "PK_846b11262368906ded5d26ac271" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_legal_documents_type" ON "legal_documents"  ("doc_type") `);
        await queryRunner.query(`CREATE INDEX "idx_legal_documents_status" ON "legal_documents"  ("status") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "token_hash" character varying(128) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, "device_info" character varying(255), CONSTRAINT "UQ_a7838d2ba25be1342091b6695f1" UNIQUE ("token_hash"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_refresh_tokens_user" ON "refresh_tokens"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions"  ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions"  ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles"  ("role_id") `);
        await queryRunner.query(`ALTER TABLE "administrative_units" ADD CONSTRAINT "FK_1d33f2501763089f6790637a923" FOREIGN KEY ("parent_id") REFERENCES "administrative_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "government_agencies" ADD CONSTRAINT "FK_c9aeaebc70a408c1cb9b4c87c3f" FOREIGN KEY ("parent_id") REFERENCES "government_agencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "government_agencies" ADD CONSTRAINT "FK_c76787ff18d8ef465257b7ccc49" FOREIGN KEY ("admin_unit_id") REFERENCES "administrative_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "procedure_requirements" ADD CONSTRAINT "FK_b7a5472bf1482b9adafa0f179a5" FOREIGN KEY ("procedure_id") REFERENCES "administrative_procedures"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "procedure_steps" ADD CONSTRAINT "FK_bd927e7767348c08a2f9ad62580" FOREIGN KEY ("procedure_id") REFERENCES "administrative_procedures"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "administrative_procedures" ADD CONSTRAINT "FK_31bea66b7daf618e389ebcf5963" FOREIGN KEY ("agency_id") REFERENCES "government_agencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_3a9ae579e61e81cc0e989afeb4a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_888a4852e27627d1ebd8a094e98" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_9b4887dbbb658dea7874063187b" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedbacks" ADD CONSTRAINT "FK_9348eb92f6de404d6e8c57c5bd0" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedbacks" ADD CONSTRAINT "FK_4334f6be2d7d841a9d5205a100e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_training_data" ADD CONSTRAINT "FK_a4abad94d9a468ea5d9c86f9f36" FOREIGN KEY ("feedback_id") REFERENCES "feedbacks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" ADD CONSTRAINT "FK_74180041ad4437e4b389830a81a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" ADD CONSTRAINT "FK_b9054dabcda324ab88fe5869da0" FOREIGN KEY ("province_id") REFERENCES "administrative_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" ADD CONSTRAINT "FK_a1982253dbc33573aa5790a6f54" FOREIGN KEY ("ward_id") REFERENCES "administrative_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" DROP CONSTRAINT "FK_a1982253dbc33573aa5790a6f54"`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" DROP CONSTRAINT "FK_b9054dabcda324ab88fe5869da0"`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" DROP CONSTRAINT "FK_74180041ad4437e4b389830a81a"`);
        await queryRunner.query(`ALTER TABLE "ai_training_data" DROP CONSTRAINT "FK_a4abad94d9a468ea5d9c86f9f36"`);
        await queryRunner.query(`ALTER TABLE "feedbacks" DROP CONSTRAINT "FK_4334f6be2d7d841a9d5205a100e"`);
        await queryRunner.query(`ALTER TABLE "feedbacks" DROP CONSTRAINT "FK_9348eb92f6de404d6e8c57c5bd0"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_9b4887dbbb658dea7874063187b"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_888a4852e27627d1ebd8a094e98"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_3a9ae579e61e81cc0e989afeb4a"`);
        await queryRunner.query(`ALTER TABLE "administrative_procedures" DROP CONSTRAINT "FK_31bea66b7daf618e389ebcf5963"`);
        await queryRunner.query(`ALTER TABLE "procedure_steps" DROP CONSTRAINT "FK_bd927e7767348c08a2f9ad62580"`);
        await queryRunner.query(`ALTER TABLE "procedure_requirements" DROP CONSTRAINT "FK_b7a5472bf1482b9adafa0f179a5"`);
        await queryRunner.query(`ALTER TABLE "government_agencies" DROP CONSTRAINT "FK_c76787ff18d8ef465257b7ccc49"`);
        await queryRunner.query(`ALTER TABLE "government_agencies" DROP CONSTRAINT "FK_c9aeaebc70a408c1cb9b4c87c3f"`);
        await queryRunner.query(`ALTER TABLE "administrative_units" DROP CONSTRAINT "FK_1d33f2501763089f6790637a923"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_tokens_user"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."idx_legal_documents_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_legal_documents_type"`);
        await queryRunner.query(`DROP TABLE "legal_documents"`);
        await queryRunner.query(`DROP TYPE "public"."legal_doc_status"`);
        await queryRunner.query(`DROP TYPE "public"."legal_doc_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_kb_chunks_source"`);
        await queryRunner.query(`DROP TABLE "kb_chunks"`);
        await queryRunner.query(`DROP TYPE "public"."kb_source_type"`);
        await queryRunner.query(`DROP INDEX "public"."uq_citizen_profiles_national_id"`);
        await queryRunner.query(`DROP INDEX "public"."uq_citizen_profiles_user"`);
        await queryRunner.query(`DROP TABLE "citizen_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."gender"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ai_training_data_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ai_training_data_source"`);
        await queryRunner.query(`DROP TABLE "ai_training_data"`);
        await queryRunner.query(`DROP TYPE "public"."training_data_status"`);
        await queryRunner.query(`DROP TYPE "public"."training_data_source"`);
        await queryRunner.query(`DROP INDEX "public"."idx_feedbacks_user"`);
        await queryRunner.query(`DROP TABLE "feedbacks"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_conversation_created"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."message_content_type"`);
        await queryRunner.query(`DROP TYPE "public"."message_sender_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_documents_purpose"`);
        await queryRunner.query(`DROP INDEX "public"."idx_documents_owner"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TYPE "public"."ocr_status"`);
        await queryRunner.query(`DROP TYPE "public"."document_purpose"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conversations_user"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP TYPE "public"."conversation_status"`);
        await queryRunner.query(`DROP TYPE "public"."conversation_channel"`);
        await queryRunner.query(`DROP INDEX "public"."uq_users_email"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."user_status"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_procedures_agency"`);
        await queryRunner.query(`DROP INDEX "public"."idx_procedures_name"`);
        await queryRunner.query(`DROP TABLE "administrative_procedures"`);
        await queryRunner.query(`DROP TYPE "public"."procedure_status"`);
        await queryRunner.query(`DROP TYPE "public"."online_level"`);
        await queryRunner.query(`DROP INDEX "public"."idx_procedure_steps_procedure"`);
        await queryRunner.query(`DROP TABLE "procedure_steps"`);
        await queryRunner.query(`DROP INDEX "public"."idx_procedure_requirements_procedure"`);
        await queryRunner.query(`DROP TABLE "procedure_requirements"`);
        await queryRunner.query(`DROP TYPE "public"."requirement_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_gov_agencies_parent"`);
        await queryRunner.query(`DROP INDEX "public"."idx_gov_agencies_level"`);
        await queryRunner.query(`DROP TABLE "government_agencies"`);
        await queryRunner.query(`DROP TYPE "public"."agency_level"`);
        await queryRunner.query(`DROP INDEX "public"."idx_admin_units_parent"`);
        await queryRunner.query(`DROP INDEX "public"."idx_admin_units_type"`);
        await queryRunner.query(`DROP TABLE "administrative_units"`);
        await queryRunner.query(`DROP TYPE "public"."admin_unit_type"`);
    }

}
